import sys
from collections import Counter
from tabnanny import verbose

from pandas import DataFrame

from kairos.adapter import to_kronos_frame
from kairos.calendars import future_timestamps

sys.path.insert(0, '.')

import argparse
import json
import sqlite3
import ta as ta_lib
from tqdm import tqdm

import matplotlib

matplotlib.use('Agg')
import os
import sys
import warnings
import numpy as np
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

sys.path.append("../")
import price_cache
from kairos.data import get_forecast_window
# model imports are deferred to _ensure_model_loaded() so --no-prediction
# runs never touch HuggingFace Hub or trigger its auth warning.
from typing import List

import pandas as pd

from kairos_orchestrator import KairosOrchestrator, OrchestratorConfig, print_results
from kairos_backtest import KairosSettings
from kairos.config import _state

plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False

# ── Configuration ────────────────────────────────────────────────────────────
# Defaults live in KairosSettings; the __main__ block calls KairosSettings.configure(args).
SYMBOL = KairosSettings.symbol
LOOKBACK = KairosSettings.lookback
PRED_LEN = KairosSettings.pred_len
PRED_SAMPLES = KairosSettings.pred_samples
INITIAL_CAPITAL = KairosSettings.initial_capital
OUTPUT_DIR = KairosSettings.output_dir

bt_tokenizer = None
bt_model = None
bt_predictor = None

_prediction_cache: dict = {}  # (symbol, last_bar_ts) -> List[pd.DataFrame]
_dist_cache: dict = {}  # (symbol, last_bar_ts) -> KairosDistribution


# ─────────────────────────────────────────────────────────────────────────────

# ── Data fetching ─────────────────────────────────────────────────────────────

def fetch_data(symbol, lookback, pred_len):
    """Return context window + actual future bars for the backtest period."""
    raw = fetch_data_raw(lookback=lookback, pred_len=pred_len, symbol=symbol)

    # Set the context cut-off to pred_len bars before the last available bar so
    # that y_ts generated by get_forecast_window falls inside the historical
    # window and we can compare predictions against real prices.
    context_end = raw.index[-(pred_len + 1)]

    x_df, x_ts, y_ts = get_forecast_window(
        symbol=symbol,
        interval=KairosSettings.interval,
        lookback=lookback,
        pred_len=pred_len,
        end=context_end,
        amount="auto",
    )

    # Ground truth: the pred_len bars that follow context_end in raw data.
    actual = raw.iloc[-pred_len:]['close'].copy()
    actual.index = pd.to_datetime(actual.index)

    return x_df, x_ts, y_ts, actual


def is_24_7_crypto_symbol(symbol: str) -> bool:
    """True for symbols that trade around the clock, 7 days a week (no weekend padding needed).

    Crypto tickers from yfinance use the "-USD" suffix (e.g. BTC-USD, ETH-USD) and trade
    24/7/365. Everything else - equities/ETFs (plain tickers, e.g. SPY, QQQ, DIA, XLK),
    FX pairs ("=X" suffix, e.g. EURUSD=X), and futures ("=F" suffix) - is closed on
    weekends (and holidays), so a naive calendar-day window undershoots the real bar count.
    """
    return symbol.endswith("-USD")


def calendar_days_for_bars(bars_needed: float, bars_per_day: float, symbol: str, buffer_days: int = 30) -> int:
    """Convert a bar count into a calendar-day window, padding for non-24/7 markets.

    Equities/ETFs and FX/futures trade roughly 5 out of every 7 days, so a naive
    bars_needed / bars_per_day calendar window undershoots real bar count by ~2/7.
    We multiply by 7/5 for those symbols (plus a small flat cushion) before adding
    the existing flat buffer_days, so the window still contains enough trading days.
    Crypto symbols (24/7) are left unpadded to preserve existing behavior.
    """
    raw_days = bars_needed / bars_per_day
    if not is_24_7_crypto_symbol(symbol):
        raw_days = raw_days * (7 / 5) + 5
    return int(raw_days) + buffer_days


def fetch_data_raw(symbol, lookback, pred_len=0, min_bars=None, as_of=None) -> DataFrame:
    price_cache.configure(remote=False)

    from datetime import date, timedelta
    interval = KairosSettings.interval
    bars_per_day = {
        "1m": 1440, "2m": 720, "5m": 288, "15m": 96, "30m": 48,
        "60m": 24, "90m": 16, "1h": 24, "1d": 1, "5d": 0.2,
        "1wk": 1 / 7, "1mo": 1 / 30, "3mo": 1 / 90,
    }.get(interval, 1)
    # Yahoo Finance hard limits by interval (days of history available)
    yf_max_days = {
        "1m": 7, "2m": 60, "5m": 60, "15m": 60, "30m": 60,
        "60m": 729, "90m": 60, "1h": 729,
    }.get(interval, 5 * 365)
    bars_needed = max(min_bars or 0, lookback + pred_len)
    days_needed = min(calendar_days_for_bars(bars_needed, bars_per_day, symbol), yf_max_days)

    end_dt = as_of.date() if as_of is not None else date.today()
    start_dt = end_dt - timedelta(days=days_needed)
    end_str, start_str = end_dt.isoformat(), start_dt.isoformat()

    raw = price_cache.get_price_data(symbol, start_date=start_str, end_date=end_str, interval=interval)
    if raw is None or raw.empty:
        raise RuntimeError(f"No price data returned for {symbol}")

    raw = raw.sort_index().copy()
    raw.columns = [c.lower() for c in raw.columns]
    idx = pd.to_datetime(raw.index)
    raw.index = idx.tz_convert(None) if idx.tz is not None else idx

    if as_of is not None:
        # Round down to the nearest bar: drop anything timestamped after
        # the simulated "now", so intraday intervals (h12/h6/1h/30m/15m/5m)
        # never leak a bar the caller couldn't actually have seen yet.
        raw = raw[raw.index <= as_of]

    if len(raw) < lookback + pred_len:
        raise RuntimeError(
            f"Not enough data for {symbol}: need {lookback + pred_len} bars, got {len(raw)}"
        )
    return raw


# ── Prediction ────────────────────────────────────────────────────────────────

def _ensure_model_loaded(model_path=None, tokenizer_path=None):
    global bt_tokenizer, bt_model, bt_predictor
    if bt_predictor is not None:
        return

    import torch
    from model import Kronos, KronosTokenizer, KronosPredictor
    tok_src = tokenizer_path or "NeoQuasar/Kronos-Tokenizer-base"
    mdl_src = model_path or "NeoQuasar/Kronos-base"
    print(f"Loading Kronos model from {mdl_src} ...")
    bt_tokenizer = KronosTokenizer.from_pretrained(tok_src)
    bt_model = Kronos.from_pretrained(mdl_src)

    from kairos_gpu import ensure_cuda
    has_cuda = ensure_cuda()

    if has_cuda:
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
        print("  → GPU mode: autocast FP16, TF32 matmuls enabled")
    else:
        import torch.nn as nn
        bt_model = torch.quantization.quantize_dynamic(
            bt_model, {nn.Linear}, dtype=torch.qint8
        )
        print(f"  → CPU mode: INT8 dynamic quantisation, {torch.get_num_threads()} threads")

    bt_predictor = KronosPredictor(bt_model, bt_tokenizer, max_context=512)


def run_model(x_df, x_ts, y_ts, pred_len, sample_count=1,
              model_path=None, tokenizer_path=None, return_samples=False):
    _ensure_model_loaded(model_path, tokenizer_path)
    return bt_predictor.predict(
        df=x_df,
        x_timestamp=x_ts,
        y_timestamp=y_ts,
        pred_len=pred_len,
        T=1.0,
        top_p=0.9,
        sample_count=sample_count,
        verbose=False,
        return_samples=return_samples,
    )


def predict_all_batch(assets: dict) -> dict:
    """Predict all assets in one batched GPU call instead of N sequential calls."""
    from kairos_meta import AssetPrediction, KairosDistribution
    import kairos_predcache

    _ensure_model_loaded()

    shared_cache = kairos_predcache.get_cache()
    shared_keys = {}  # symbol -> cache key (only computed when shared_cache is active)

    df_list, x_ts_list, y_ts_list = [], [], []
    cached_results = {}
    uncached_symbols = []

    for symbol, df in assets.items():
        cache_key = (symbol, df.index[-1])
        if cache_key in _prediction_cache:
            cached_results[symbol] = _prediction_cache[cache_key]
            continue

        if shared_cache is not None:
            lookback_for_hash = min(KairosSettings.lookback, len(df))
            content_hash = kairos_predcache.content_hash_for_closes(
                df["close"].iloc[-lookback_for_hash:]
            )
            shared_key = kairos_predcache.make_key(
                symbol=symbol,
                interval=KairosSettings.interval,
                bar_timestamp=df.index[-1],
                lookback_len=lookback_for_hash,
                pred_samples=KairosSettings.pred_samples,
                model_id=KairosSettings.model,
                content_hash=content_hash,
            )
            shared_keys[symbol] = shared_key
            shared_hit = shared_cache.get(shared_key)
            if shared_hit is not None:
                _prediction_cache[cache_key] = shared_hit
                cached_results[symbol] = shared_hit
                continue

        lookback = min(KairosSettings.lookback, len(df))
        x_df, x_ts = to_kronos_frame(df, lookback, amount="auto")
        y_ts = future_timestamps(x_ts.iloc[-1], KairosSettings.interval, 1, _state.calendar, _state.tz)
        df_list.append(x_df)
        x_ts_list.append(x_ts)
        y_ts_list.append(y_ts)
        uncached_symbols.append(symbol)

    if uncached_symbols:
        seq_lens = [x.shape[0] for x in df_list]
        return_samples = KairosSettings.pred_samples > 1
        if len(set(seq_lens)) == 1:
            pred_lists = bt_predictor.predict_batch(
                df_list, x_ts_list, y_ts_list,
                pred_len=1, sample_count=KairosSettings.pred_samples, return_samples=return_samples, verbose=False
            )
        else:
            pred_lists = [
                bt_predictor.predict(df, x_ts, y_ts, pred_len=1, sample_count=KairosSettings.pred_samples,
                                     return_samples=return_samples, verbose=False)
                for df, x_ts, y_ts in zip(df_list, x_ts_list, y_ts_list)
            ]
        for symbol, preds in zip(uncached_symbols, pred_lists):
            if not isinstance(preds, list):
                preds = [preds]
            _prediction_cache[(symbol, assets[symbol].index[-1])] = preds
            cached_results[symbol] = preds
            if shared_cache is not None and symbol in shared_keys:
                shared_cache.put(shared_keys[symbol], preds)

    result = {}
    for symbol, preds in cached_results.items():
        dist_key = (symbol, assets[symbol].index[-1])
        dist = _dist_cache.get(dist_key)
        if dist is None:
            from kairos_backtest import distribution_for
            dist = distribution_for(preds)
            _dist_cache[dist_key] = dist
        result[symbol] = AssetPrediction(
            symbol=symbol,
            dist=dist,
            current_price=float(assets[symbol]["close"].iloc[-1]),
            history=assets[symbol],
        )
    return result


# ── Backtest engine ───────────────────────────────────────────────────────────

def backtest(predicted_close: pd.Series, actual_close: pd.Series,
             initial_capital: float, threshold: float):
    """
    Signal rule: if predicted daily return > threshold → buy;
                 if predicted daily return < -threshold → sell / short.
    P&L is computed on actual close prices.
    """
    pred = predicted_close.reset_index(drop=True)
    n = min(len(pred), len(actual_close))
    price = actual_close.iloc[:n].reset_index(drop=True)

    capital = initial_capital
    position = 0  # shares held (negative = short)
    trades = []
    equity = []

    for i in range(n):
        p = float(price.iloc[i])
        if pd.isna(p):
            equity.append(capital + position * (price.dropna().iloc[0] if position else 0))
            continue

        # Signal from predicted return
        if i < len(pred) - 1:
            pred_ret = (float(pred.iloc[i + 1]) - float(pred.iloc[i])) / float(pred.iloc[i])
        else:
            pred_ret = 0.0

        target_pos = 1 if pred_ret > threshold else (-1 if pred_ret < -threshold else 0)

        if target_pos != np.sign(position):
            # Close existing position
            if position != 0:
                capital += position * p
                trades.append(dict(day=i, action='CLOSE', price=p,
                                   shares=position, capital=capital))
                position = 0
            # Open new position
            if target_pos != 0:
                shares = int(capital / p) * target_pos
                position = shares
                capital -= shares * p
                trades.append(dict(day=i, action='BUY' if target_pos > 0 else 'SHORT',
                                   price=p, shares=shares, capital=capital))

        portfolio_val = capital + position * p
        equity.append(portfolio_val)

    # Close any open position at end
    if position != 0 and n > 0:
        last_p = float(price.iloc[n - 1])
        capital += position * last_p
        trades.append(dict(day=n - 1, action='CLOSE', price=last_p,
                           shares=position, capital=capital))

    equity_series = pd.Series(equity, index=actual_close.index[:n])
    return equity_series, trades


def compute_metrics(equity: pd.Series, initial_capital: float, trades: list):
    rets = equity.pct_change().dropna()
    total_ret = (equity.iloc[-1] - initial_capital) / initial_capital
    annual_ret = (1 + total_ret) ** (252 / max(len(rets), 1)) - 1
    vol = rets.std() * np.sqrt(252)
    sharpe = (annual_ret - 0.03) / vol if vol > 0 else 0.0
    peak = equity.expanding().max()
    max_dd = ((equity - peak) / peak).min()
    trade_pairs = [(t['price'], trades[i + 1]['price'])
                   for i, t in enumerate(trades[:-1])
                   if t['action'] in ('BUY', 'SHORT') and
                   trades[i + 1]['action'] == 'CLOSE']
    trade_rets = [(s - b) / b for b, s in trade_pairs]
    win_rate = (sum(1 for r in trade_rets if r > 0) / len(trade_rets)
                if trade_rets else 0.0)
    return dict(total_return=total_ret, annual_return=annual_ret,
                volatility=vol, sharpe=sharpe, max_drawdown=max_dd,
                win_rate=win_rate, trades=len(trades),
                final_capital=equity.iloc[-1])


# ── Signal parsing ────────────────────────────────────────────────────────────

def parse_signals_config(signals_str):
    """Parse '--signals' CLI string into a config dict."""
    if not signals_str or signals_str.lower() == 'none':
        return {}
    config = {
        'sma_periods': [],
        'ema_periods': [],
        'bb': None,
        'rsi': None,
        'stoch': None,
        'macd': None,
    }
    for token in signals_str.split(','):
        t = token.strip().upper()
        if t.startswith('SMA_'):
            config['sma_periods'].append(int(t[4:]))
        elif t.startswith('EMA_'):
            config['ema_periods'].append(int(t[4:]))
        elif t.startswith('BB_'):
            config['bb'] = {'period': int(t[3:]), 'std': 2.0}
        elif t == 'BB':
            config['bb'] = {'period': 20, 'std': 2.0}
        elif t == 'RSI':
            config['rsi'] = {'period': 14}
        elif t == 'STOCH':
            config['stoch'] = {'k': 14, 'd': 3}
        elif t == 'MACD':
            config['macd'] = {'fast': 12, 'slow': 26, 'signal_period': 9}
    return config


# ── Signal computation ────────────────────────────────────────────────────────

def compute_signals(df, config):
    """
    Compute technical signals from a date-indexed OHLCV DataFrame using pandas_ta.
    Pass context + backtest period so rolling windows warm up correctly.
    Returns dict of signal_name -> pd.Series (same index as df).
    """
    if not config:
        return {}

    close = df['close']
    high = df['high'] if 'high' in df.columns else close
    low = df['low'] if 'low' in df.columns else close
    out = {}

    for period in config.get('sma_periods', []):
        out[f'SMA_{period}'] = ta_lib.trend.SMAIndicator(close, window=period).sma_indicator()

    for period in config.get('ema_periods', []):
        out[f'EMA_{period}'] = ta_lib.trend.EMAIndicator(close, window=period).ema_indicator()

    bb = config.get('bb')
    if bb:
        bb_ind = ta_lib.volatility.BollingerBands(close, window=bb['period'], window_dev=bb['std'])
        out['BB_upper'] = bb_ind.bollinger_hband()
        out['BB_lower'] = bb_ind.bollinger_lband()
        out['BB_mid'] = bb_ind.bollinger_mavg()

    rsi_cfg = config.get('rsi')
    if rsi_cfg:
        out['RSI'] = ta_lib.momentum.RSIIndicator(close, window=rsi_cfg['period']).rsi()

    stoch = config.get('stoch')
    if stoch:
        stoch_ind = ta_lib.momentum.StochasticOscillator(
            high, low, close, window=stoch['k'], smooth_window=stoch['d']
        )
        out['STOCH_K'] = stoch_ind.stoch()
        out['STOCH_D'] = stoch_ind.stoch_signal()

    macd = config.get('macd')
    if macd:
        macd_ind = ta_lib.trend.MACD(
            close, window_slow=macd['slow'], window_fast=macd['fast'], window_sign=macd['signal_period']
        )
        out['MACD_line'] = macd_ind.macd()
        out['MACD_signal'] = macd_ind.macd_signal()
        out['MACD_hist'] = macd_ind.macd_diff()

    return out


# ── Interactive control panel ─────────────────────────────────────────────────

def predict_kairos_cloud(signal: pd.DataFrame = None, **kwargs) -> List[pd.DataFrame]:
    pred_historic = kwargs.get('pred_historic', 0)
    pred_num = kwargs.get('pred_num', 1)
    model_path = kwargs.get("model") or KairosSettings.model or "NeoQuasar/Kronos-base"
    tokenizer_path = kwargs.get("tokenizer") or KairosSettings.tokenizer or "NeoQuasar/Kronos-Tokenizer-base"
    symbol = kwargs.get("symbol") or KairosSettings.symbol
    lookback = KairosSettings.lookback
    pred_samples = KairosSettings.pred_samples

    if signal is None:
        print("Kairos prediction cloud")
        print(f"   Symbol:             {symbol}")
        print(f"   Context window:     {lookback} bars")
        print(f"   Samples per bar:    {pred_samples} x")
        print()
        print("Step 1: Fetching data ...")
        x_df, x_ts, y_ts, actual = fetch_data(symbol, lookback, pred_historic)
    else:
        cache_key = (symbol, signal.index[-1])
        if cache_key in _prediction_cache:
            return _prediction_cache[cache_key]
        lookback = min(KairosSettings.lookback, len(signal))
        x_df, x_ts = to_kronos_frame(signal, lookback, amount="auto")
        y_ts = future_timestamps(x_ts.iloc[-1], KairosSettings.interval, 1, _state.calendar, _state.tz)

    result_list = run_model(
        x_df, x_ts, y_ts[:1], pred_num,
        sample_count=pred_samples,
        model_path=model_path, tokenizer_path=tokenizer_path,
        return_samples=(pred_samples > 1),
    )
    if not isinstance(result_list, list):
        result_list = [result_list]

    if signal is not None:
        _prediction_cache[cache_key] = result_list
    return result_list


def _parse_period(period: str) -> tuple:
    """Parse a human period string into (count, unit).

    Args:
        period: Period string, e.g., '6m', '1y', '3m', '2w', '10d'

    Returns:
        Tuple of (count: int, unit: str)

    Raises:
        ValueError: If period format is invalid
    """
    import re as _re
    m = _re.fullmatch(r"(\d+)(d|w|m|y)", period.strip().lower())
    if not m:
        raise ValueError(
            f"Unrecognised backtest_period {period!r}. Use e.g. '6m', '1y', '3m', '2w', '10d'."
        )
    return int(m.group(1)), m.group(2)


def _period_to_bars(period: str, interval: str) -> int:
    """Convert a human period string (e.g. '6m', '1y') to a bar count."""
    n, unit = _parse_period(period)
    cal_days = {"d": n, "w": n * 7, "m": n * 30, "y": n * 365}[unit]
    bars_per_day = {
        "1m": 1440, "2m": 720, "5m": 288, "15m": 96, "30m": 48,
        "60m": 24, "90m": 16, "1h": 24, "1d": 1, "5d": 0.2,
        "1wk": 1 / 7, "1mo": 1 / 30, "3mo": 1 / 90,
    }.get(interval, 1)
    return max(1, int(cal_days * bars_per_day))


def _period_to_weeks(period: str) -> float:
    """Convert a human period string (e.g. '6m', '1y') to weeks.

    Uses 365.25 days per year and 7 days per week.
    Matches the period parsing from _period_to_bars.
    """
    n, unit = _parse_period(period)
    # Convert to calendar days: use 365.25 days/year, 30.4375 days/month (365.25/12)
    cal_days = {
        "d": n,
        "w": n * 7,
        "m": n * 365.25 / 12,
        "y": n * 365.25,
    }[unit]
    # Convert calendar days to weeks (7 days per week)
    return cal_days / 7


_COMMODITY_ETFS = {"GLD", "SLV", "USO", "UNG", "DBC", "PDBC", "CPER", "COPX", "GDX"}


def asset_class_for(assets) -> str:
    """Classify a group of tickers into crypto/fx/commodity/equity/mixed.

    Rules: crypto tickers end in "-USD", fx tickers end in "=X", commodity
    tickers end in "=F" or are one of the known commodity ETFs
    (GLD/SLV/USO/UNG/DBC/PDBC/CPER/COPX/GDX). Everything else is equity.
    A group's class is the majority class of its symbols; if no single
    class has a strict majority, the group is "mixed".
    """
    classes = []
    for sym in assets:
        s = sym.strip()
        if s.endswith("-USD"):
            classes.append("crypto")
        elif s.endswith("=X"):
            classes.append("fx")
        elif s.endswith("=F") or s in _COMMODITY_ETFS:
            classes.append("commodity")
        else:
            classes.append("equity")
    if not classes:
        return "mixed"
    counts = Counter(classes)
    top_class, top_count = counts.most_common(1)[0]
    if top_count * 2 > len(classes):
        return top_class
    return "mixed"


# Disabled strategies per (interval, asset_class) fallback, used when no
# oracle-tested DB profile (data/pipeline_results.db, disabled_strategies
# table, keyed on the exact (interval, sorted-assets) pair) exists for the
# (interval, assets) pair - see resolve_disabled_strategies() below.
#
# Derived from the 2026-07-05 oracle (--no-prediction) shadow sweep at
# interval=1d, backtest_period=3m, across 27 asset groups (7 crypto, 10
# equity, 3 fx, 7 commodity/mixed-commodity). Rule: a strategy is disabled
# for a class if EITHER
#   (a) it had negative sharpe in >=60% of that class's groups AND
#       >=10 total signals across the class (avoids disabling on noise), OR
#   (b) mean sharpe (degenerate |sharpe|>1000 outliers excluded) <= -5.0
#       with >=2 groups negative.
# Mean sharpe values in the comments are the capped/filtered means used to
# apply the rule above.
_DISABLED_BY_CLASS: dict = {
    ("1d", "crypto"): {
        "volume_fade",              # mean sharpe -153.74, neg 6/6
        "cross_asset_spread",       # mean sharpe  -93.02, neg 5/6
        "volume_confirmation",      # mean sharpe  -36.64, neg 6/6
        "funding_rate_prediction",  # mean sharpe  -27.70, neg 6/6
        "path_v_shape",             # mean sharpe  -11.07, neg 6/6
        "bsts_decomposition",       # mean sharpe   -9.70, neg 6/6
        "rsi_divergence",           # mean sharpe   -9.33, neg 4/7
        "particle_filter",          # mean sharpe   -8.89, neg 6/6
        "inverse_variance",         # mean sharpe   -8.57, neg 6/6
        "dynamic_bracket",          # mean sharpe   -8.42, neg 6/6
        "close_direction",          # mean sharpe   -8.14, neg 6/6
        "hmm_regime",               # mean sharpe   -7.33, neg 3/6
        "distribution_overlap",     # mean sharpe   -6.63, neg 6/6
        "conditional_path",         # mean sharpe   -6.02, neg 6/6
    },
    ("1d", "commodity"): {
        "volume_fade",              # mean sharpe  -70.09, neg 6/6
        "tail_asymmetry",           # mean sharpe  -21.15, neg 4/6
        "rsi_filter",               # mean sharpe  -15.10, neg 5/6
        "cross_asset_spread",       # mean sharpe  -12.16, neg 2/5
        "volume_confirmation",      # mean sharpe  -10.05, neg 6/7
        "funding_rate_prediction",  # mean sharpe   -8.51, neg 7/7
        "hmm_regime",               # mean sharpe   -6.43, neg 4/6
        "distribution_overlap",     # mean sharpe   -5.94, neg 6/7
    },
    ("1d", "equity"): {
        "volume_fade",              # mean sharpe  -48.73, neg 4/7
        "rsi_filter",               # mean sharpe  -12.45, neg 7/10
        "tail_asymmetry",           # mean sharpe  -11.35, neg 6/10
        "funding_rate_prediction",  # mean sharpe  -11.10, neg 10/10
        "volume_confirmation",      # mean sharpe   -5.84, neg 9/10
        "distribution_overlap",     # mean sharpe   -4.80, neg 9/10 (>=60%, >=10 sig rule)
        "hmm_regime",               # mean sharpe   -4.48, neg 9/10 (>=60%, >=10 sig rule)
        "skew",                     # mean sharpe   -4.04, neg 7/10 (>=60%, >=10 sig rule)
        "conditional_path",         # mean sharpe   -1.18, neg 7/10 (>=60%, >=10 sig rule)
    },
    ("1d", "fx"): {
        "tail_asymmetry",           # mean sharpe  -12.26, neg 3/3
        "cross_asset_spread",       # mean sharpe   -8.31, neg 2/3
        "hmm_regime",               # mean sharpe   -5.29, neg 3/3
        "funding_rate_prediction",  # mean sharpe   -3.75, neg 3/3 (>=60%, >=10 sig rule)
        "distribution_overlap",     # mean sharpe   -2.68, neg 2/3 (>=60%, >=10 sig rule)
        "conditional_path",         # mean sharpe   -0.90, neg 2/3 (>=60%, >=10 sig rule)
    },
}


# Repo-root / DB-path derivation, matching kairos_signals.py's pattern. Kept
# as module constants for readability, but resolve_disabled_strategies()
# recomputes the actual path used per-call (when db_path is None) rather than
# baking DEFAULT_DB_PATH in at import time, so tests can override db_path and
# a fresh clone (no data/ dir yet) doesn't fail at import.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DB_PATH = os.path.join(REPO_ROOT, "data", "pipeline_results.db")


def resolve_disabled_strategies(interval: str, assets, db_path: str = None) -> set:
    """Resolve the set of disabled strategy names for a run.

    Resolution order:
      1. If data/pipeline_results.db's oracle_results table has ANY row for
         the exact (interval, sorted-assets-key) profile - i.e. the profile
         has been oracle-tested - return the (possibly empty) set of
         strategy names found in that DB's disabled_strategies table for the
         same profile. An empty result here is meaningful ("tested and
         clean") and does NOT fall through to the class fallback.
      2. Otherwise (profile never oracle-tested, DB missing, or any sqlite3
         error), fall back to (interval, asset_class) in _DISABLED_BY_CLASS,
         where asset_class is computed via asset_class_for(assets).
      3. Empty set if neither matches.

    `db_path` defaults to None, resolving to DEFAULT_DB_PATH at call time
    (not baked in at import time) so tests can point at a temp DB. Never
    imports kairos_pipeline (would create an import cycle) - plain sqlite3
    only, opened/closed per call.

    Note: this assumes oracle_results.assets was written with a consistently
    sorted CSV for a given profile going forward (run_stage_oracle /
    refresh_disabled_strategies in kairos_pipeline.py normalize independently
    at insert time); legacy rows written by an unsorted direct CLI call are a
    pre-existing data-quality issue out of scope here.
    """
    if db_path is None:
        db_path = DEFAULT_DB_PATH

    assets_key = ",".join(sorted(assets))
    cls = asset_class_for(assets)
    class_fallback = _DISABLED_BY_CLASS.get((interval, cls), set())

    conn = None
    try:
        conn = sqlite3.connect(db_path)
        tested = conn.execute(
            "SELECT 1 FROM oracle_results WHERE interval=? AND assets=? LIMIT 1",
            (interval, assets_key),
        ).fetchone()
        if tested is None:
            return class_fallback
        rows = conn.execute(
            "SELECT strategy_name FROM disabled_strategies WHERE interval=? AND assets=?",
            (interval, assets_key),
        ).fetchall()
        return {r[0] for r in rows}
    except sqlite3.Error:
        return class_fallback
    finally:
        if conn is not None:
            conn.close()


_DEFAULT_ASSETS = ["BTC-USD", "ETH-USD", "SOL-USD"]


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Kairos walk-forward backtest - Strategies based on predictions")
    parser.add_argument("--model", metavar="PATH", default=None,
                        help="Local path to finetuned Kronos predictor (defaults to NeoQuasar/Kronos-base)")
    parser.add_argument("--tokenizer", metavar="PATH", default=None,
                        help="Local path to Kronos tokenizer (defaults to NeoQuasar/Kronos-Tokenizer-base)")
    parser.add_argument("--symbol", metavar="SYM", default=SYMBOL,
                        help=f"Trading symbol (default {SYMBOL})")
    parser.add_argument("--interval", metavar="INTERVAL", default=None, dest="interval",
                        help='Bar size: "1d", "1h", "15m", etc. (default: 1d)')
    parser.add_argument("--assets", nargs="+", metavar="SYM", default=None, dest="assets",
                        help=f"Asset tickers to backtest (default: {' '.join(_DEFAULT_ASSETS)})")
    parser.add_argument("--backtest_period", metavar="PERIOD", default=None, dest="backtest_period",
                        help='Backtest duration: "6m", "1y", "3m", "2w", "10d", etc. (default: 6m)')
    parser.add_argument("--lookback", metavar="N", default=LOOKBACK, type=int,
                        help=f"Context window bars (default {LOOKBACK})")
    parser.add_argument("--pred_samples", metavar="N", default=PRED_SAMPLES, type=int,
                        help=f"Samples per bar (default {PRED_SAMPLES})")
    parser.add_argument("--initial_capital", metavar="N", default=INITIAL_CAPITAL, type=float,
                        help=f"Initial capital (default {INITIAL_CAPITAL})")
    parser.add_argument("--no-prediction", dest="no_prediction", action="store_true", default=False,
                        help="Replace model predictions with actual next-bar OHLCV (oracle baseline)")
    parser.add_argument("--export_json", metavar="PATH", default=None, dest="export_json",
                        help="Additionally dump summary/strategy_rankings/shadow_performance to this JSON path")
    parser.add_argument("--no_disabled_filter", dest="no_disabled_filter", action="store_true", default=False,
                        help="Bypass DB/class disabled-strategy resolution; evaluate every strategy "
                             "(used by the oracle pipeline stage)")

    args = parser.parse_args()
    KairosSettings.configure(args)

    assets = KairosSettings.assets or _DEFAULT_ASSETS
    if args.no_disabled_filter:
        disabled = set()
        print(f"  [info] --no_disabled_filter set - bypassing disabled-strategy resolution, all strategies enabled.")
    else:
        disabled = resolve_disabled_strategies(KairosSettings.interval, assets)
        if not disabled:
            profile_key = (KairosSettings.interval, ",".join(sorted(assets)))
            print(f"  [info] No oracle-tested disabled-strategy profile or class fallback for {profile_key} - all strategies enabled.")

    DEMO_BACKTEST_OVER_N_BARS = _period_to_bars(KairosSettings.backtest_period, KairosSettings.interval)

    config = OrchestratorConfig(
        initial_capital=KairosSettings.initial_capital,
        cross_asset_ranking=True,
        online_weighting=True,
        partial_exits=True,
        max_horizon=3,
        no_prediction=KairosSettings.no_prediction,
        disabled_strategies=disabled,
    )

    orchestrator = KairosOrchestrator(
        predict_fn=predict_kairos_cloud,
        assets=assets,
        config=config,
        batch_predict_fn=predict_all_batch,
        model=KairosSettings.model,
        tokenizer=KairosSettings.tokenizer,
        symbol=KairosSettings.symbol,
    )

    lookback = KairosSettings.lookback
    results = orchestrator.run_backtest({
        sym: fetch_data_raw(sym, lookback, min_bars=lookback + DEMO_BACKTEST_OVER_N_BARS)
                 .tail(lookback + DEMO_BACKTEST_OVER_N_BARS)
        for sym in assets
    }, lookback=lookback)

    top_results = orchestrator.backtest_top_strategies(results, n=len(results["strategy_rankings"]))
    print_results(results, top_results)

    if args.export_json:
        # Additive-only: minimal JSON dump for the pipeline's oracle/model stages.
        # Does not alter stdout output or any behavior when the flag is absent.
        def _jsonable(obj):
            if isinstance(obj, dict):
                return {k: _jsonable(v) for k, v in obj.items()}
            if isinstance(obj, (list, tuple)):
                return [_jsonable(v) for v in obj]
            if isinstance(obj, np.generic):
                return obj.item()
            return obj

        export_payload = {
            "summary": _jsonable(results.get("summary", {})),
            "strategy_rankings": _jsonable(results.get("strategy_rankings", [])),
            "shadow_performance": _jsonable(results.get("shadow_performance", {})),
            "strategy_build_stats": _jsonable(results.get("strategy_build_stats", {})),
            "signal_firing_count": _jsonable(results.get("signal_firing_count", 0)),
        }
        with open(args.export_json, "w") as _f:
            json.dump(export_payload, _f, indent=2)
        print(f"  [export_json] wrote {args.export_json}")
