import sys

from pandas import DataFrame

from kairos.adapter import to_kronos_frame
from kairos.calendars import future_timestamps

sys.path.insert(0, '.')

import argparse
import ta as ta_lib
from tqdm import tqdm

import matplotlib

matplotlib.use('Agg')
import os
import sys
import warnings
import numpy as np
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

sys.path.append("../")
import price_cache
from kairos.data import get_forecast_window
from model import Kronos, KronosTokenizer, KronosPredictor
from typing import List

import pandas as pd

from kairos_orchestrator import KairosOrchestrator, OrchestratorConfig, print_results
from kairos.config import _state

plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False

# ── Configuration ────────────────────────────────────────────────────────────
SYMBOL = "BTC-USD"  # yfinance format
LOOKBACK = 300  # bars fed to Kronos as context
PRED_LEN = 60  # bars Kronos forecasts (= backtest period)
PRED_SAMPLES = 100  # Prediction samples to average with
INITIAL_CAPITAL = 100_000  # CNY
OUTPUT_DIR = "./output"

# ─────────────────────────────────────────────────────────────────────────────

# ── Data fetching ─────────────────────────────────────────────────────────────

def fetch_data(symbol, lookback, pred_len):
    """Return context window + actual future bars for the backtest period."""
    raw = fetch_data_raw(lookback=lookback, pred_len=pred_len, symbol=symbol)

    # Set the context cut-off to pred_len bars before the last available bar so
    # that y_ts generated by get_forecast_window falls inside the historical
    # window and we can compare predictions against real prices.
    context_end = raw.index[-(pred_len + 1)]

    x_df, x_ts, y_ts = get_forecast_window(
        symbol=symbol,
        interval="1d",
        lookback=lookback,
        pred_len=pred_len,
        end=context_end,
        amount="auto",
    )

    # Ground truth: the pred_len bars that follow context_end in raw data.
    actual = raw.iloc[-pred_len:]['close'].copy()
    actual.index = pd.to_datetime(actual.index)

    return x_df, x_ts, y_ts, actual


def fetch_data_raw(symbol, lookback, pred_len = 0) -> DataFrame:
    price_cache.configure(remote=False)

    from datetime import date
    end_str = date.today().isoformat()
    start_str = str(int(end_str[:4]) - 5) + end_str[4:]  # 5 years back

    raw = price_cache.get_price_data(symbol, start_date=start_str, end_date=end_str, interval="1d")
    if raw is None or raw.empty:
        raise RuntimeError(f"No price data returned for {symbol}")

    raw = raw.sort_index().copy()
    raw.columns = [c.lower() for c in raw.columns]
    raw.index = pd.to_datetime(raw.index).tz_localize(None)

    if len(raw) < lookback + pred_len:
        raise RuntimeError(
            f"Not enough data for {symbol}: need {lookback + pred_len} bars, got {len(raw)}"
        )
    return raw


# ── Prediction ────────────────────────────────────────────────────────────────

def run_model(x_df, x_ts, y_ts, pred_len, sample_count=1,
              model_path=None, tokenizer_path=None):
    global bt_tokenizer, bt_model, bt_predictor
    if bt_tokenizer is None or bt_model is None or bt_predictor is None:
        tok_src = tokenizer_path or "NeoQuasar/Kronos-Tokenizer-base"
        mdl_src = model_path or "NeoQuasar/Kronos-base"
        print(f"Loading Kronos model from {mdl_src} ...")
        bt_tokenizer = KronosTokenizer.from_pretrained(tok_src)
        bt_model = Kronos.from_pretrained(mdl_src)
        bt_predictor = KronosPredictor(bt_model, bt_tokenizer, max_context=512)

    # print("Running prediction ...")
    pred_df = bt_predictor.predict(
        df=x_df,
        x_timestamp=x_ts,
        y_timestamp=y_ts,
        pred_len=pred_len,
        T=1.0,
        top_p=0.9,
        sample_count=sample_count,
        verbose=pred_len > 1,
    )
    return pred_df

# ── Backtest engine ───────────────────────────────────────────────────────────

def backtest(predicted_close: pd.Series, actual_close: pd.Series,
             initial_capital: float, threshold: float):
    """
    Signal rule: if predicted daily return > threshold → buy;
                 if predicted daily return < -threshold → sell / short.
    P&L is computed on actual close prices.
    """
    pred = predicted_close.reset_index(drop=True)
    n = min(len(pred), len(actual_close))
    price = actual_close.iloc[:n].reset_index(drop=True)

    capital = initial_capital
    position = 0  # shares held (negative = short)
    trades = []
    equity = []

    for i in range(n):
        p = float(price.iloc[i])
        if pd.isna(p):
            equity.append(capital + position * (price.dropna().iloc[0] if position else 0))
            continue

        # Signal from predicted return
        if i < len(pred) - 1:
            pred_ret = (float(pred.iloc[i + 1]) - float(pred.iloc[i])) / float(pred.iloc[i])
        else:
            pred_ret = 0.0

        target_pos = 1 if pred_ret > threshold else (-1 if pred_ret < -threshold else 0)

        if target_pos != np.sign(position):
            # Close existing position
            if position != 0:
                capital += position * p
                trades.append(dict(day=i, action='CLOSE', price=p,
                                   shares=position, capital=capital))
                position = 0
            # Open new position
            if target_pos != 0:
                shares = int(capital / p) * target_pos
                position = shares
                capital -= shares * p
                trades.append(dict(day=i, action='BUY' if target_pos > 0 else 'SHORT',
                                   price=p, shares=shares, capital=capital))

        portfolio_val = capital + position * p
        equity.append(portfolio_val)

    # Close any open position at end
    if position != 0 and n > 0:
        last_p = float(price.iloc[n - 1])
        capital += position * last_p
        trades.append(dict(day=n - 1, action='CLOSE', price=last_p,
                           shares=position, capital=capital))

    equity_series = pd.Series(equity, index=actual_close.index[:n])
    return equity_series, trades

def compute_metrics(equity: pd.Series, initial_capital: float, trades: list):
    rets = equity.pct_change().dropna()
    total_ret = (equity.iloc[-1] - initial_capital) / initial_capital
    annual_ret = (1 + total_ret) ** (252 / max(len(rets), 1)) - 1
    vol = rets.std() * np.sqrt(252)
    sharpe = (annual_ret - 0.03) / vol if vol > 0 else 0.0
    peak = equity.expanding().max()
    max_dd = ((equity - peak) / peak).min()
    trade_pairs = [(t['price'], trades[i + 1]['price'])
                   for i, t in enumerate(trades[:-1])
                   if t['action'] in ('BUY', 'SHORT') and
                   trades[i + 1]['action'] == 'CLOSE']
    trade_rets = [(s - b) / b for b, s in trade_pairs]
    win_rate = (sum(1 for r in trade_rets if r > 0) / len(trade_rets)
                if trade_rets else 0.0)
    return dict(total_return=total_ret, annual_return=annual_ret,
                volatility=vol, sharpe=sharpe, max_drawdown=max_dd,
                win_rate=win_rate, trades=len(trades),
                final_capital=equity.iloc[-1])

# ── Signal parsing ────────────────────────────────────────────────────────────

def parse_signals_config(signals_str):
    """Parse '--signals' CLI string into a config dict."""
    if not signals_str or signals_str.lower() == 'none':
        return {}
    config = {
        'sma_periods': [],
        'ema_periods': [],
        'bb': None,
        'rsi': None,
        'stoch': None,
        'macd': None,
    }
    for token in signals_str.split(','):
        t = token.strip().upper()
        if t.startswith('SMA_'):
            config['sma_periods'].append(int(t[4:]))
        elif t.startswith('EMA_'):
            config['ema_periods'].append(int(t[4:]))
        elif t.startswith('BB_'):
            config['bb'] = {'period': int(t[3:]), 'std': 2.0}
        elif t == 'BB':
            config['bb'] = {'period': 20, 'std': 2.0}
        elif t == 'RSI':
            config['rsi'] = {'period': 14}
        elif t == 'STOCH':
            config['stoch'] = {'k': 14, 'd': 3}
        elif t == 'MACD':
            config['macd'] = {'fast': 12, 'slow': 26, 'signal_period': 9}
    return config

# ── Signal computation ────────────────────────────────────────────────────────

def compute_signals(df, config):
    """
    Compute technical signals from a date-indexed OHLCV DataFrame using pandas_ta.
    Pass context + backtest period so rolling windows warm up correctly.
    Returns dict of signal_name -> pd.Series (same index as df).
    """
    if not config:
        return {}

    close = df['close']
    high = df['high'] if 'high' in df.columns else close
    low = df['low'] if 'low' in df.columns else close
    out = {}

    for period in config.get('sma_periods', []):
        out[f'SMA_{period}'] = ta_lib.trend.SMAIndicator(close, window=period).sma_indicator()

    for period in config.get('ema_periods', []):
        out[f'EMA_{period}'] = ta_lib.trend.EMAIndicator(close, window=period).ema_indicator()

    bb = config.get('bb')
    if bb:
        bb_ind = ta_lib.volatility.BollingerBands(close, window=bb['period'], window_dev=bb['std'])
        out['BB_upper'] = bb_ind.bollinger_hband()
        out['BB_lower'] = bb_ind.bollinger_lband()
        out['BB_mid'] = bb_ind.bollinger_mavg()

    rsi_cfg = config.get('rsi')
    if rsi_cfg:
        out['RSI'] = ta_lib.momentum.RSIIndicator(close, window=rsi_cfg['period']).rsi()

    stoch = config.get('stoch')
    if stoch:
        stoch_ind = ta_lib.momentum.StochasticOscillator(
            high, low, close, window=stoch['k'], smooth_window=stoch['d']
        )
        out['STOCH_K'] = stoch_ind.stoch()
        out['STOCH_D'] = stoch_ind.stoch_signal()

    macd = config.get('macd')
    if macd:
        macd_ind = ta_lib.trend.MACD(
            close, window_slow=macd['slow'], window_fast=macd['fast'], window_sign=macd['signal_period']
        )
        out['MACD_line'] = macd_ind.macd()
        out['MACD_signal'] = macd_ind.macd_signal()
        out['MACD_hist'] = macd_ind.macd_diff()

    return out

# ── Interactive control panel ─────────────────────────────────────────────────

def predict_kairos_cloud(signal: pd.DataFrame = None, pred_historic=0, pred_num=1, **kwargs) -> List[pd.DataFrame]:
    if kwargs == None:
        kwargs = {}

    kwargs.model = kwargs.model or "NeoQuasar/Kronos-base"  # Local path to finetuned Kronos predictor (defaults to NeoQuasar/Kronos-base)")
    kwargs.tokenizer = kwargs.tokenizer or "NeoQuasar/Kronos-Tokenizer-base" # Local path to Kronos tokenizer (defaults to NeoQuasar/Kronos-Tokenizer-base)")
    kwargs.output = kwargs.output or os.path.join(OUTPUT_DIR, f"{kwargs.symbol.replace('.', '_')}_backtest_results.html") # Output HTML path (defaults to ./output/<symbol>_backtest_results.html)")
    kwargs.symbol = kwargs.symbol or SYMBOL  # Trading symbol (default {SYMBOL})")
    kwargs.lookback = LOOKBACK  # Context window bars (default {LOOKBACK})")
    kwargs.pred_samples = PRED_SAMPLES  # Samples per bar (default {PRED_SAMPLES})")

    print("Kairos Walk-Forward Backtest (HTML output)")
    print(f"   Symbol:             {kwargs.symbol}")
    print(f"   Context window:     {kwargs.lookback} bars")
    print(f"   Samples per bar:    {kwargs.pred_samples} x")
    print()

    if not signal:
        print("Step 1: Fetching data ...")
        x_df, x_ts, y_ts, actual = fetch_data(kwargs.symbol, kwargs.lookback, pred_historic)
    else:
        x_df, x_ts = to_kronos_frame(signal, kwargs.lookback, amount="auto")
        y_ts = future_timestamps( x_ts.iloc[-1], "1d", 1, _state.calendar, _state.tz)

    result_list = []
    for sample in range(kwargs.pred_samples):
        result_list += [run_model(x_df, x_ts, y_ts[:1], pred_num,
                                  model_path=kwargs.model, tokenizer_path=kwargs.tokenizer, )]
    return result_list

if __name__ == "__main__":
    config = OrchestratorConfig(
        initial_capital=100000.0,
        cross_asset_ranking=True,
        online_weighting=True,
        partial_exits=True,
        max_horizon=3,
    )

    orchestrator = KairosOrchestrator(
        predict_fn=predict_kairos_cloud,
        assets=["BTC-USD", "ETH-USD", "SOL-USD"],
        config=config,
    )

    results = orchestrator.run_backtest({
        "BTC-USD": fetch_data_raw("BTC-USD", 300),
        "ETH-USD": fetch_data_raw("ETH-USD", 300),
        "SOL-USD": fetch_data_raw("SOL-USD", 300),
    }, lookback=300)

    print_results(results)