"""
run_backtest_kronos.py

Walk-forward backtest: Kronos predicts the next PRED_LEN bars from a historical
context window; the strategy trades on predicted direction vs actual close prices.

Data is fetched live via price_cache - no local CSV files required.

Usage:
    python run_backtest_kronos.py

Output:
    - ./output/<symbol>_backtest_results.png
"""
import matplotlib
matplotlib.use('Agg')
import os
import sys
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

sys.path.append("../")
import price_cache
from kairos.data import get_forecast_window
from model import Kronos, KronosTokenizer, KronosPredictor

plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False

# ── Configuration ────────────────────────────────────────────────────────────
SYMBOL          = "000831.SZ"   # yfinance format (SZ = Shenzhen)
# SYMBOL          = "BTC-USD"   # yfinance format
LOOKBACK        = 300           # bars fed to Kronos as context
PRED_LEN        = 60            # bars Kronos forecasts (= backtest period)
INITIAL_CAPITAL = 100_000       # CNY
THRESHOLD       = 0.02          # predicted daily return to trigger a trade
OUTPUT_DIR      = "./output"
# ─────────────────────────────────────────────────────────────────────────────


# ── Data fetching ─────────────────────────────────────────────────────────────

def fetch_data(symbol, lookback, pred_len):
    """Return context window + actual future bars for the backtest period."""
    price_cache.configure(remote=False)

    from datetime import date
    end_str   = date.today().isoformat()
    start_str = str(int(end_str[:4]) - 5) + end_str[4:]   # 5 years back

    raw = price_cache.get_price_data(symbol, start_date=start_str, end_date=end_str, interval="1d")
    if raw is None or raw.empty:
        raise RuntimeError(f"No price data returned for {symbol}")

    raw = raw.sort_index().copy()
    raw.columns = [c.lower() for c in raw.columns]
    raw.index   = pd.to_datetime(raw.index).tz_localize(None)

    if len(raw) < lookback + pred_len:
        raise RuntimeError(
            f"Not enough data for {symbol}: need {lookback + pred_len} bars, got {len(raw)}"
        )

    # Set the context cut-off to pred_len bars before the last available bar so
    # that y_ts generated by get_forecast_window falls inside the historical
    # window and we can compare predictions against real prices.
    context_end = raw.index[-(pred_len + 1)]

    x_df, x_ts, y_ts = get_forecast_window(
        symbol=symbol,
        interval="1d",
        lookback=lookback,
        pred_len=pred_len,
        end=context_end,
        amount="auto",
    )

    # Ground truth: the pred_len bars that follow context_end in raw data.
    actual = raw.iloc[-pred_len:]['close'].copy()
    actual.index = pd.to_datetime(actual.index)

    return x_df, x_ts, y_ts, actual


# ── Prediction ────────────────────────────────────────────────────────────────

def run_model(x_df, x_ts, y_ts, pred_len):
    print("Loading Kronos model ...")
    tokenizer = KronosTokenizer.from_pretrained("NeoQuasar/Kronos-Tokenizer-base")
    model     = Kronos.from_pretrained("NeoQuasar/Kronos-base")
    predictor = KronosPredictor(model, tokenizer, max_context=512)

    print("Running prediction ...")
    pred_df = predictor.predict(
        df=x_df,
        x_timestamp=x_ts,
        y_timestamp=y_ts,
        pred_len=pred_len,
        T=1.0,
        top_p=0.9,
        sample_count=1,
        verbose=True,
    )
    return pred_df


# ── Backtest engine ───────────────────────────────────────────────────────────

def backtest(predicted_close: pd.Series, actual_close: pd.Series,
             initial_capital: float, threshold: float):
    """
    Signal rule: if predicted daily return > threshold → buy;
                 if predicted daily return < -threshold → sell / short.
    P&L is computed on actual close prices.
    """
    pred  = predicted_close.reset_index(drop=True)
    n     = min(len(pred), len(actual_close))
    price = actual_close.iloc[:n].reset_index(drop=True)

    capital  = initial_capital
    position = 0          # shares held (negative = short)
    trades   = []
    equity   = []

    for i in range(n):
        p = float(price.iloc[i])
        if pd.isna(p):
            equity.append(capital + position * (price.dropna().iloc[0] if position else 0))
            continue

        # Signal from predicted return
        if i < len(pred) - 1:
            pred_ret = (float(pred.iloc[i + 1]) - float(pred.iloc[i])) / float(pred.iloc[i])
        else:
            pred_ret = 0.0

        target_pos = 1 if pred_ret > threshold else (-1 if pred_ret < -threshold else 0)

        if target_pos != np.sign(position):
            # Close existing position
            if position != 0:
                capital += position * p
                trades.append(dict(day=i, action='CLOSE', price=p,
                                   shares=position, capital=capital))
                position = 0
            # Open new position
            if target_pos != 0:
                shares   = int(capital / p) * target_pos
                position = shares
                capital -= shares * p
                trades.append(dict(day=i, action='BUY' if target_pos > 0 else 'SHORT',
                                   price=p, shares=shares, capital=capital))

        portfolio_val = capital + position * p
        equity.append(portfolio_val)

    # Close any open position at end
    if position != 0 and n > 0:
        last_p = float(price.iloc[n - 1])
        capital += position * last_p
        trades.append(dict(day=n - 1, action='CLOSE', price=last_p,
                           shares=position, capital=capital))

    equity_series = pd.Series(equity, index=actual_close.index[:n])
    return equity_series, trades


def compute_metrics(equity: pd.Series, initial_capital: float, trades: list):
    rets = equity.pct_change().dropna()
    total_ret   = (equity.iloc[-1] - initial_capital) / initial_capital
    annual_ret  = (1 + total_ret) ** (252 / max(len(rets), 1)) - 1
    vol         = rets.std() * np.sqrt(252)
    sharpe      = (annual_ret - 0.03) / vol if vol > 0 else 0.0
    peak        = equity.expanding().max()
    max_dd      = ((equity - peak) / peak).min()
    trade_pairs = [(t['price'], trades[i + 1]['price'])
                   for i, t in enumerate(trades[:-1])
                   if t['action'] in ('BUY', 'SHORT') and
                      trades[i + 1]['action'] == 'CLOSE']
    trade_rets  = [(s - b) / b for b, s in trade_pairs]
    win_rate    = (sum(1 for r in trade_rets if r > 0) / len(trade_rets)
                   if trade_rets else 0.0)
    return dict(total_return=total_ret, annual_return=annual_ret,
                volatility=vol, sharpe=sharpe, max_drawdown=max_dd,
                win_rate=win_rate, trades=len(trades),
                final_capital=equity.iloc[-1])


# ── Plotting ──────────────────────────────────────────────────────────────────

def plot_results(equity, actual_close, pred_close, metrics, symbol, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    fig, axes = plt.subplots(3, 1, figsize=(14, 10))

    # 1. Equity vs benchmark
    ax = axes[0]
    benchmark = actual_close / actual_close.iloc[0] * equity.iloc[0]
    ax.plot(equity.index,    equity.values,    label='Strategy',      linewidth=2)
    ax.plot(benchmark.index, benchmark.values, label='Buy-and-Hold',  linewidth=2, alpha=0.7)
    ax.axhline(equity.iloc[0], color='grey', linestyle='--', linewidth=1)
    ax.set_ylabel('Portfolio Value (CNY)')
    ax.set_title(f'{symbol} - Kronos Walk-Forward Backtest', fontweight='bold')
    ax.legend()
    ax.grid(True, alpha=0.3)
    metrics_txt = (f"Return: {metrics['total_return']:.1%}  "
                   f"Sharpe: {metrics['sharpe']:.2f}  "
                   f"MaxDD: {metrics['max_drawdown']:.1%}  "
                   f"WinRate: {metrics['win_rate']:.0%}  "
                   f"Trades: {metrics['trades']}")
    ax.set_xlabel(metrics_txt, fontsize=9)

    # 2. Predicted vs actual close
    ax = axes[1]
    ax.plot(actual_close.index, actual_close.values, label='Actual',    linewidth=2)
    ax.plot(actual_close.index[:len(pred_close)],
            pred_close.values[:len(actual_close)],   label='Predicted', linewidth=2,
            linestyle='--', alpha=0.8)
    ax.set_ylabel('Close Price')
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 3. Drawdown
    ax = axes[2]
    peak     = equity.expanding().max()
    drawdown = (equity - peak) / peak
    ax.fill_between(drawdown.index, drawdown.values, 0, alpha=0.4, color='red')
    ax.set_ylabel('Drawdown')
    ax.set_xlabel('Date')
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    path = os.path.join(output_dir, f"{symbol.replace('.', '_')}_backtest_results.png")
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close('all')
    print(f"Chart saved: {path}")


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("🤖 Kronos Walk-Forward Backtest")
    print(f"   Symbol:          {SYMBOL}")
    print(f"   Context window:  {LOOKBACK} bars")
    print(f"   Backtest period: {PRED_LEN} bars")
    print(f"   Initial capital: {INITIAL_CAPITAL:,.0f} CNY")
    print(f"   Trade threshold: {THRESHOLD:.0%}")
    print()

    print("Step 1: Fetching data ...")
    x_df, x_ts, y_ts, actual_close = fetch_data(SYMBOL, LOOKBACK, PRED_LEN)
    print(f"  Context : {len(x_df)} bars  ({x_ts.iloc[0].date()} → {x_ts.iloc[-1].date()})")
    print(f"  Actuals : {len(actual_close)} bars matched in price history")

    pred_df = run_model(x_df, x_ts, y_ts, PRED_LEN)
    pred_close = pd.Series(pred_df['close'].values)

    print("\nStep 2: Running backtest ...")
    if actual_close.empty:
        # Future dates - no ground truth yet; use predicted prices as stand-in
        print("  No actual prices for prediction period yet (future dates).")
        print("  Using predicted prices to simulate signal-only backtest.")
        actual_close = pred_close.copy()
        actual_close.index = pd.to_datetime(y_ts.values)

    equity, trades = backtest(pred_close, actual_close, INITIAL_CAPITAL, THRESHOLD)
    metrics = compute_metrics(equity, INITIAL_CAPITAL, trades)

    print("\n=== Backtest Report ===")
    print(f"  Total Return  : {metrics['total_return']:+.2%}")
    print(f"  Annual Return : {metrics['annual_return']:+.2%}")
    print(f"  Sharpe Ratio  : {metrics['sharpe']:.2f}")
    print(f"  Max Drawdown  : {metrics['max_drawdown']:.2%}")
    print(f"  Win Rate      : {metrics['win_rate']:.0%}")
    print(f"  Trades        : {metrics['trades']}")
    print(f"  Final Capital : {metrics['final_capital']:,.0f} CNY")

    plot_results(equity, actual_close, pred_close, metrics, SYMBOL, OUTPUT_DIR)
    print("\nDone.")
