"""
run_backtest_kronos.py

Walk-forward backtest: Kronos predicts the next PRED_LEN bars from a historical
context window; the strategy trades on predicted direction vs actual close prices.

Data is fetched live via price_cache — no local CSV files required.

Usage:
    python run_backtest_kronos.py [--model PATH] [--tokenizer PATH]

Output:
    - ./output/<symbol>_backtest_results.png
"""
import argparse
import matplotlib
from huggingface_hub.utils import tqdm
from pandas import DataFrame

matplotlib.use('Agg')
import os
import sys
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

sys.path.append("../")
import price_cache
from kairos.data import get_forecast_window
from model import Kronos, KronosTokenizer, KronosPredictor

plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False

# ── Configuration ────────────────────────────────────────────────────────────
# SYMBOL          = "000831.SZ"   # yfinance format (SZ = Shenzhen)
SYMBOL = "BTC-USD"  # yfinance format
LOOKBACK = 300  # bars fed to Kronos as context
PRED_LEN = 60  # bars Kronos forecasts (= backtest period)
PRED_SAMPLES = 100  # Prediction samples to average with
INITIAL_CAPITAL = 100_000  # CNY
THRESHOLD = 0.02  # predicted daily return to trigger a trade
OUTPUT_DIR = "./output"


# ─────────────────────────────────────────────────────────────────────────────


# ── Data fetching ─────────────────────────────────────────────────────────────

def fetch_data(symbol, lookback, pred_len):
    """Return context window + actual future bars for the backtest period."""
    price_cache.configure(remote=False)

    from datetime import date
    end_str = date.today().isoformat()
    start_str = str(int(end_str[:4]) - 5) + end_str[4:]  # 5 years back

    raw = price_cache.get_price_data(symbol, start_date=start_str, end_date=end_str, interval="1d")
    if raw is None or raw.empty:
        raise RuntimeError(f"No price data returned for {symbol}")

    raw = raw.sort_index().copy()
    raw.columns = [c.lower() for c in raw.columns]
    raw.index = pd.to_datetime(raw.index).tz_localize(None)

    if len(raw) < lookback + pred_len:
        raise RuntimeError(
            f"Not enough data for {symbol}: need {lookback + pred_len} bars, got {len(raw)}"
        )

    # Set the context cut-off to pred_len bars before the last available bar so
    # that y_ts generated by get_forecast_window falls inside the historical
    # window and we can compare predictions against real prices.
    context_end = raw.index[-(pred_len + 1)]

    # auto convert/compute amount
    if "amount" in raw.columns and raw["amount"].notna().all():
        raw["amount"] = raw["amount"].astype("float64")
    elif "vwap" in raw.columns and raw["vwap"].notna().all():
        raw["amount"] = (raw["vwap"] * raw["Volume"]).astype("float64")
    else:
        raw["amount"] = raw["close"] * raw["volume"]

    x_df, x_ts, y_ts = get_forecast_window(
        symbol=symbol,
        interval="1d",
        lookback=lookback,
        pred_len=pred_len,
        end=context_end,
        amount="auto",
    )

    # Ground truth: the pred_len bars that follow context_end in raw data.
    actual = raw.iloc[-pred_len:].copy()
    actual.index = pd.to_datetime(actual.index)

    return x_df, x_ts, y_ts, actual


# ── Prediction ────────────────────────────────────────────────────────────────

bt_tokenizer = None
bt_model = None
bt_predictor = None


def run_model(x_df, x_ts, y_ts, pred_len, sample_count=1,
              model_path=None, tokenizer_path=None):
    global bt_tokenizer, bt_model, bt_predictor
    if bt_tokenizer is None or bt_model is None or bt_predictor is None:
        tok_src = tokenizer_path or "NeoQuasar/Kronos-Tokenizer-base"
        mdl_src = model_path or "NeoQuasar/Kronos-base"
        print(f"Loading Kronos model from {mdl_src} ...")
        bt_tokenizer = KronosTokenizer.from_pretrained(tok_src)
        bt_model = Kronos.from_pretrained(mdl_src)
        bt_predictor = KronosPredictor(bt_model, bt_tokenizer, max_context=512)

    # print("Running prediction ...")
    pred_df = bt_predictor.predict(
        df=x_df,
        x_timestamp=x_ts,
        y_timestamp=y_ts,
        pred_len=pred_len,
        T=1.0,
        top_p=0.9,
        sample_count=sample_count,
        verbose=pred_len > 1,
    )
    return pred_df


# ── Backtest engine ───────────────────────────────────────────────────────────

def backtest(predicted_close: pd.Series, actual_close: pd.Series,
             initial_capital: float, threshold: float):
    """
    Signal rule: if predicted daily return > threshold → buy;
                 if predicted daily return < -threshold → sell / short.
    P&L is computed on actual close prices.
    """
    pred = predicted_close.reset_index(drop=True)
    n = min(len(pred), len(actual_close))
    price = actual_close.iloc[:n].reset_index(drop=True)

    capital = initial_capital
    position = 0  # shares held (negative = short)
    trades = []
    equity = []

    for i in range(n):
        p = float(price.iloc[i])
        if pd.isna(p):
            equity.append(capital + position * (price.dropna().iloc[0] if position else 0))
            continue

        # Signal from predicted return
        if i < len(pred) - 1:
            pred_ret = (float(pred.iloc[i + 1]) - float(pred.iloc[i])) / float(pred.iloc[i])
        else:
            pred_ret = 0.0

        target_pos = 1 if pred_ret > threshold else (-1 if pred_ret < -threshold else 0)

        if target_pos != np.sign(position):
            # Close existing position
            if position != 0:
                capital += position * p
                trades.append(dict(day=i, action='CLOSE', price=p,
                                   shares=position, capital=capital))
                position = 0
            # Open new position
            if target_pos != 0:
                shares = int(capital / p) * target_pos
                position = shares
                capital -= shares * p
                trades.append(dict(day=i, action='BUY' if target_pos > 0 else 'SHORT',
                                   price=p, shares=shares, capital=capital))

        portfolio_val = capital + position * p
        equity.append(portfolio_val)

    # Close any open position at end
    if position != 0 and n > 0:
        last_p = float(price.iloc[n - 1])
        capital += position * last_p
        trades.append(dict(day=n - 1, action='CLOSE', price=last_p,
                           shares=position, capital=capital))

    equity_series = pd.Series(equity, index=actual_close.index[:n])
    return equity_series, trades


def compute_metrics(equity: pd.Series, initial_capital: float, trades: list):
    rets = equity.pct_change().dropna()
    total_ret = (equity.iloc[-1] - initial_capital) / initial_capital
    annual_ret = (1 + total_ret) ** (252 / max(len(rets), 1)) - 1
    vol = rets.std() * np.sqrt(252)
    sharpe = (annual_ret - 0.03) / vol if vol > 0 else 0.0
    peak = equity.expanding().max()
    max_dd = ((equity - peak) / peak).min()
    trade_pairs = [(t['price'], trades[i + 1]['price'])
                   for i, t in enumerate(trades[:-1])
                   if t['action'] in ('BUY', 'SHORT') and
                   trades[i + 1]['action'] == 'CLOSE']
    trade_rets = [(s - b) / b for b, s in trade_pairs]
    win_rate = (sum(1 for r in trade_rets if r > 0) / len(trade_rets)
                if trade_rets else 0.0)
    return dict(total_return=total_ret, annual_return=annual_ret,
                volatility=vol, sharpe=sharpe, max_drawdown=max_dd,
                win_rate=win_rate, trades=len(trades),
                final_capital=equity.iloc[-1])


# ── Plotting ──────────────────────────────────────────────────────────────────

def plot_results(equity, actual_close, pred_close, metrics, symbol, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    fig, axes = plt.subplots(3, 1, figsize=(14, 10))

    # 1. Equity vs benchmark
    ax = axes[0]
    benchmark = actual_close / actual_close.iloc[0] * equity.iloc[0]
    ax.plot(equity.index, equity.values, label='Strategy', linewidth=2)
    ax.plot(benchmark.index, benchmark.values, label='Buy-and-Hold', linewidth=2, alpha=0.7)
    ax.axhline(equity.iloc[0], color='grey', linestyle='--', linewidth=1)
    ax.set_ylabel('Portfolio Value (CNY)')
    ax.set_title(f'{symbol} — Kronos Walk-Forward Backtest', fontweight='bold')
    ax.legend()
    ax.grid(True, alpha=0.3)
    metrics_txt = (f"Return: {metrics['total_return']:.1%}  "
                   f"Sharpe: {metrics['sharpe']:.2f}  "
                   f"MaxDD: {metrics['max_drawdown']:.1%}  "
                   f"WinRate: {metrics['win_rate']:.0%}  "
                   f"Trades: {metrics['trades']}")
    ax.set_xlabel(metrics_txt, fontsize=9)

    # 2. Predicted vs actual close
    ax = axes[1]
    ax.plot(actual_close.index, actual_close.values, label='Actual', linewidth=2)
    ax.plot(actual_close.index[:len(pred_close)],
            pred_close.values[:len(actual_close)], label='Predicted', linewidth=2,
            linestyle='--', alpha=0.8)
    ax.set_ylabel('Close Price')
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 3. Drawdown
    ax = axes[2]
    peak = equity.expanding().max()
    drawdown = (equity - peak) / peak
    ax.fill_between(drawdown.index, drawdown.values, 0, alpha=0.4, color='red')
    ax.set_ylabel('Drawdown')
    ax.set_xlabel('Date')
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    path = os.path.join(output_dir, f"{symbol.replace('.', '_')}_backtest_results.png")
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close('all')
    print(f"Chart saved: {path}")

def plot_results_candlesticks(equity, actual, predicted, metrics, symbol,
                              output_path, model_label):
    actual_close = actual["close"]

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    fig, axes = plt.subplots(4, 1, figsize=(14, 13),
                             gridspec_kw={'height_ratios': [3, 3, 2, 1.2]})

    # 1. Equity vs benchmark
    ax = axes[0]
    benchmark = actual_close / actual_close.iloc[0] * equity.iloc[0]
    ax.plot(equity.index, equity.values, label='Strategy', linewidth=2)
    ax.plot(benchmark.index, benchmark.values, label='Buy-and-Hold', linewidth=2, alpha=0.7)
    ax.axhline(equity.iloc[0], color='grey', linestyle='--', linewidth=1)
    ax.set_ylabel('Portfolio Value (CNY)')
    ax.set_title(f'{symbol} — Kronos Walk-Forward Backtest', fontweight='bold')
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 2. Candlestick chart — Actual (left) and Predicted (right) per bar
    ax = axes[1]
    n = min(len(actual), len(predicted))
    xs = np.arange(n)
    w = 0.35  # half-width of each candle body

    def _candles(ax, xs, ohlc, offset, color, alpha=0.85):
        for i, (_, row) in enumerate(ohlc.iterrows()):
            o, h, l, c = row['open'], row['high'], row['low'], row['close']
            x = xs[i] + offset
            ax.plot([x, x], [l, h], color=color, linewidth=0.8, alpha=alpha)
            ax.add_patch(plt.Rectangle(
                (x - w / 2, min(o, c)), w, abs(c - o),
                color=color, alpha=alpha,
            ))

    _candles(ax, xs, actual.iloc[:n],    offset=-w / 2, color='#26a69a')
    _candles(ax, xs, predicted.iloc[:n], offset=+w / 2, color='#42a5f5')

    tick_step = max(1, n // 10)
    ax.set_xticks(xs[::tick_step])
    ax.set_xticklabels([actual.index[i].strftime('%Y-%m-%d') for i in xs[::tick_step]],
                       rotation=30, ha='right', fontsize=7)
    ax.set_xlim(-0.5, n - 0.5)
    ax.set_ylabel('Price')
    from matplotlib.patches import Patch
    ax.legend(handles=[
        Patch(color='#26a69a', label='Actual'),
        Patch(color='#42a5f5', label='Predicted'),
    ], fontsize=7)
    ax.grid(True, alpha=0.3)

    # 3. Drawdown
    ax = axes[2]
    peak = equity.expanding().max()
    drawdown = (equity - peak) / peak
    ax.fill_between(drawdown.index, drawdown.values, 0, alpha=0.4, color='red')
    ax.set_ylabel('Drawdown')
    ax.set_xlabel('Date')
    ax.grid(True, alpha=0.3)

    # 4. Report text panel
    ax = axes[3]
    ax.axis('off')
    report_lines = [
        f"Model:          {model_label}",
        f"Total Return:   {metrics['total_return']:+.2%}    "
        f"Annual Return:  {metrics['annual_return']:+.2%}    "
        f"Sharpe:         {metrics['sharpe']:.2f}",
        f"Max Drawdown:   {metrics['max_drawdown']:.2%}    "
        f"Win Rate:       {metrics['win_rate']:.0%}          "
        f"Trades:         {metrics['trades']}",
        f"Final Capital:  {metrics['final_capital']:,.0f} CNY",
    ]
    ax.text(0.01, 0.95, '\n'.join(report_lines),
            transform=ax.transAxes, fontsize=8.5,
            verticalalignment='top', fontfamily='monospace',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#f5f5f5', alpha=0.8))

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close('all')
    print(f"Chart saved: {output_path}")


# ── Entry point ───────────────────────────────────────────────────────────────

def trimmed_mean(df: DataFrame, trim_max_factor=0.10) -> DataFrame:
    retVal = {}
    for column in df.columns:
        Q1 = df[column].quantile(trim_max_factor)
        Q3 = df[column].quantile(1.0 - trim_max_factor)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        retVal[column] = df.loc[(df[column] >= lower) & (df[column] <= upper), column].mean()
    return DataFrame([retVal], index=[df.index[0]])

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Kairos walk-forward backtest")
    parser.add_argument("--model", metavar="PATH", default=None,
                        help="Local path to finetuned Kronos predictor (defaults to NeoQuasar/Kronos-base)")
    parser.add_argument("--tokenizer", metavar="PATH", default=None,
                        help="Local path to Kronos tokenizer (defaults to NeoQuasar/Kronos-Tokenizer-base)")
    parser.add_argument("--output", metavar="PATH", default=None,
                        help="Output PNG path (defaults to ./output/<symbol>_backtest_results.png)")
    args = parser.parse_args()

    _model_label = args.model or "NeoQuasar/Kronos-base"
    _output_path = args.output or os.path.join(OUTPUT_DIR, f"{SYMBOL.replace('.', '_')}_backtest_results.png")

    print("🤖 Kairos Walk-Forward Backtest")
    print(f"   Symbol:          {SYMBOL}")
    print(f"   Context window:  {LOOKBACK} bars")
    print(f"   Backtest period: {PRED_LEN} bars")
    print(f"   samples per bar: {PRED_SAMPLES} x")
    print(f"   Initial capital: {INITIAL_CAPITAL:,.0f}")
    print(f"   Trade threshold: {THRESHOLD:.0%}")
    print()

    print("Step 1: Fetching data ...")
    x_df, x_ts, y_ts, actual = fetch_data(SYMBOL, LOOKBACK, PRED_LEN)
    actual_full = actual.copy()
    actual_close = actual["close"]
    print(f"  Context : {len(x_df)} bars  ({x_ts.iloc[0].date()} → {x_ts.iloc[-1].date()})")
    print(f"  Actuals : {len(actual_close)} bars matched in price history")

    pred_all = []
    for pred_step in tqdm(range(PRED_LEN), desc="Walking steps"):

        result_list = []
        for sample in range(PRED_SAMPLES):
            result_list += [run_model(x_df, x_ts, y_ts[:1], 1,
                                      model_path=args.model, tokenizer_path=args.tokenizer)]
        pred_all_df = pd.concat(result_list, ignore_index=True)
        pred_all += [trimmed_mean(pred_all_df)]

        # pred_all += [run_model(x_df, x_ts, y_ts[:1], 1, PRED_SAMPLES)]

        actual_first = actual[:1]
        x_df.index = x_ts.values
        x_df = pd.concat([x_df.iloc[1:], actual_first[x_df.columns]])
        x_ts = pd.Series(x_df.index, name="x_timestamp")
        x_df = x_df.reset_index(drop=True)
        y_ts = y_ts.iloc[1:]
        actual = actual[1:]

    pred_all = pd.concat(pred_all)
    pred_close = pd.Series(pred_all['close'].values)

    print("\nStep 2: Running backtest ...")
    if actual_close.empty:
        raise Exception("No Close data")

    equity, trades = backtest(pred_close, actual_close, INITIAL_CAPITAL, THRESHOLD)
    metrics = compute_metrics(equity, INITIAL_CAPITAL, trades)

    print("\n=== Backtest Report ===")
    print(f"  Total Return  : {metrics['total_return']:+.2%}")
    print(f"  Annual Return : {metrics['annual_return']:+.2%}")
    print(f"  Sharpe Ratio  : {metrics['sharpe']:.2f}")
    print(f"  Max Drawdown  : {metrics['max_drawdown']:.2%}")
    print(f"  Win Rate      : {metrics['win_rate']:.0%}")
    print(f"  Trades        : {metrics['trades']}")
    print(f"  Final Capital : {metrics['final_capital']:,.0f} CNY")

    # plot_results(equity, actual_close, pred_close, metrics, SYMBOL, OUTPUT_DIR)
    plot_results_candlesticks(equity, actual_full, pred_all, metrics, SYMBOL,
                              _output_path, _model_label)
    print("\nDone.")
